/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as BridgesRouteImport } from './routes/bridges'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActorsIdRouteImport } from './routes/actors.$id'

const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgesRoute = BridgesRouteImport.update({
  id: '/bridges',
  path: '/bridges',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsIdRoute = ActorsIdRouteImport.update({
  id: '/actors/$id',
  path: '/actors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridges': typeof BridgesRoute
  '/ecosystem': typeof EcosystemRoute
  '/network': typeof NetworkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weekly': typeof WeeklyRoute
  '/actors/$id': typeof ActorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridges': typeof BridgesRoute
  '/ecosystem': typeof EcosystemRoute
  '/network': typeof NetworkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weekly': typeof WeeklyRoute
  '/actors/$id': typeof ActorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bridges': typeof BridgesRoute
  '/ecosystem': typeof EcosystemRoute
  '/network': typeof NetworkRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/weekly': typeof WeeklyRoute
  '/actors/$id': typeof ActorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bridges'
    | '/ecosystem'
    | '/network'
    | '/sitemap.xml'
    | '/weekly'
    | '/actors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bridges'
    | '/ecosystem'
    | '/network'
    | '/sitemap.xml'
    | '/weekly'
    | '/actors/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bridges'
    | '/ecosystem'
    | '/network'
    | '/sitemap.xml'
    | '/weekly'
    | '/actors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BridgesRoute: typeof BridgesRoute
  EcosystemRoute: typeof EcosystemRoute
  NetworkRoute: typeof NetworkRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WeeklyRoute: typeof WeeklyRoute
  ActorsIdRoute: typeof ActorsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridges': {
      id: '/bridges'
      path: '/bridges'
      fullPath: '/bridges'
      preLoaderRoute: typeof BridgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/$id': {
      id: '/actors/$id'
      path: '/actors/$id'
      fullPath: '/actors/$id'
      preLoaderRoute: typeof ActorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BridgesRoute: BridgesRoute,
  EcosystemRoute: EcosystemRoute,
  NetworkRoute: NetworkRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WeeklyRoute: WeeklyRoute,
  ActorsIdRoute: ActorsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
